services:
  - mongodb
  - postgresql
  - redis-server
language: go
install: false
go:
  - "1.10.x"
env:
  global:
    - PATH=${PATH}:./bin
    - POP_PATH=$PWD/cmd/proxy
    - GO_ENV=test_postgres
    - MINIO_ACCESS_KEY=minio
    - MINIO_SECRET_KEY=minio123
    - ATHENS_MONGO_STORAGE_URL=mongodb://127.0.0.1:27017
    - CODE_COV=1
    - GO_BINARY_PATH=vgo
    - TMPDIR=/tmp/
before_script:
  - make setup-dev-env
  - wget "https://dl.minio.io/server/minio/release/linux-amd64/minio"
  - chmod +x minio && nohup ./minio server . &
  - buffalo db create
  - buffalo db migrate up
script:
  - make verify test-unit
after_success:
  - if [ "${CODE_COV}" == "1" ]; then
      curl -s https://codecov.io/bash -o codecov && bash codecov -X fix;
    else
      echo codecov not enabled;
    fi
